- name: Wait for systems to boot up
  hosts: crdb
  gather_facts: no
  any_errors_fatal: true
  tasks:
    - name: Wait up to 300 seconds
      wait_for_connection:
        delay: 3
        sleep: 5
        timeout: 300

- name: OS updates
  hosts: crdb
  gather_facts: true
  gather_subset:
    - "distribution"
    - "distribution_release"
    - "distribution_major_version"
    - "distribution_version"
    - "os_family"
  any_errors_fatal: true
  become: true
  roles:
    - ansible_role_kernel_update
    - ansible_role_chrony
    - ansible_role_mount_disks


#- name: Deploy CockroachDB
#  hosts: crdb
#  gather_facts: true
  #gather_subset:
  #  - "distribution"
  #  - "distribution_release"
  #  - "distribution_major_version"
  #  - "distribution_version"
  #  - "os_family"
  #  - "all_ipv4_addresses"
  #  - "all_ipv6_addresses"
  #  - "system"
  #  - ""
#  any_errors_fatal: true
#  vars:
    # use_hosts_file: True
#  roles:
#    - ansible_role_crdb