- name: create group
  ansible.builtin.group:
    name: "{{ crdb_service_group }}"
    state: present

- name: add service user and group
  ansible.builtin.user:
    name: "{{ crdb_service_user }}"
    groups: "{{ crdb_service_group }}"
    shell: /sbin/nologin
    create_home: no
    append: yes
    comment: "CockroachDB nologin user"
    state: present