- name: print distribution
  ansible.builtin.debug:
    msg: "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.{{ ansible_distribution_major_version }}"

- name: include distribution and version-specific vars
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.{{ ansible_distribution_major_version }}.yml"

- name: update kernel for vmw_ptp support (Debian/Ubuntu)
  ansible.builtin.apt:
    name:
      - "{{ apt_kernel_6_package }}"
  register: kernel_st
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: rebooting machine
  ansible.builtin.reboot:
    reboot_timeout: 300
  when: kernel_st.changed
