- name: include OS specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: validate ptp0 exist
  ansible.builtin.stat:
    path: "{{ ptp_device }}"
  register: stat_st

- name: Fail if the ptp device does not exist
  ansible.builtin.fail:
    msg: "PTP device does not exist: {{ ptp_device }"
  when: not stat_st.stat.exists

- name: install and configure chrony (Debian/Ubuntu)
  ansible.builtin.include_tasks: debian.yml
  when: ansible_os_family == 'Debian'

- name: install and configure chrony (RedHat/CentOS)
  ansible.builtin.include_tasks: redhat.yml
  when: ansible_os_family == 'RedHat'