- name: set variables
  ansible.builtin.set_fact:
    tmp_folder: /tmp
    cockroach_folder: /usr/local/bin
    cockroach_library_folder: /usr/local/lib/cockroach

- name: download and extract Cockroach DB executable
  ansible.builtin.unarchive:
    src: "{{ crdb_url }}"
    dest: "{{ tmp_folder }}"
    remote_src: yes

- name: extract cockroach version
  ansible.builtin.set_fact:
    crdb_version: "{{ ((crdb_url | basename) | splitext)[0] }}"

- name: print cockroach version
  ansible.builtin.debug:
    var: crdb_version

- name: copy executable
  ansible.builtin.copy:
    remote_src: yes
    src: "{{ tmp_folder }}/{{ crdb_version }}/cockroach"
    dest: "{{ cockroach_folder }}"
    mode: 555

- name: create cockroach library directory
  ansible.builtin.file:
    path: "{{ cockroach_library_folder }}"
    state: directory
    mode: '0644'

- name: copy cockroach geos libraries
  ansible.builtin.copy:
    remote_src: yes
    src: "{{ tmp_folder }}/{{ crdb_version }}/lib/{{ item }}"
    dest: "{{ cockroach_library_folder }}"
    mode: 444
  with_items:
    - libgeos.so
    - libgeos_c.so
