#
# Ref. https://www.cockroachlabs.com/docs/stable/deploy-cockroachdb-on-premises
#
- name: set variables
  ansible.builtin.set_fact:
    cert_folders:
      - certs
      - my-safe-directory
    cert_files:
      - ca.crt
      - node.crt
      - node.key
    crdb_lb_items: "{{ ( crdb_lb_ip | default([]) ) + ( crdb_lb_hostnames | default([]) ) }}"

- name: delete local certificate folder on ansible host
  local_action: file path=certificates state=absent

- name: delete previous certificate folders on node 0
  ansible.builtin.file:
    state: absent
    path: "{{ item }}/"
  with_items: "{{ cert_folders }}"
  when: inventory_hostname == play_hosts[0]

- name: create certificate directories on bootstrap node
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0750'
  with_items: "{{ cert_folders }}"
  when: inventory_hostname == play_hosts[0]

- name: create node certificate folders
  file:
    path: "certs/{{ item }}"
    state: directory
    mode: '0750'
  with_items: "{{ play_hosts }}"
  when: inventory_hostname == play_hosts[0]

- name: generate CA certificate and key
  ansible.builtin.shell:
    cmd: >
      cockroach cert create-ca 
      --certs-dir=certs 
      --ca-key=my-safe-directory/ca.key 
      --overwrite
  when: inventory_hostname == play_hosts[0]

- name: copy CA certificate to ansible host
  ansible.builtin.copy:
    remote_src: true
    src: certs/ca.crt
    dest: "certs/{{ item }}/ca.crt"
  with_items: "{{ play_hosts }}"
  when: inventory_hostname == play_hosts[0]

- name: copy CA key to ansible host
  ansible.builtin.copy:
    remote_src: true
    src: my-safe-directory/ca.key
    dest: "certs/{{ item }}/ca.key"
  with_items: "{{ play_hosts }}"
  when: inventory_hostname == play_hosts[0]

- name: generate crdb node certificates
  ansible.builtin.shell:
    cmd: >
      cockroach cert create-node 
      {{ item }}
      {{ hostvars[item]['ansible_fqdn'] }}
      {{ hostvars[item]['ansible_hostname'] }}
      localhost
      127.0.0.1
      {{ crdb_lb_items | join(' ') }}
      --certs-dir=certs/{{ item }}
      --ca-key=my-safe-directory/ca.key
  with_items: "{{ play_hosts }}"
  when: inventory_hostname == play_hosts[0]

- name: generate cockroach 'root' user certificate
  ansible.builtin.shell:
    cmd: >
      cockroach cert create-client 
      root
      --certs-dir=certs/{{ item }}
      --ca-key=my-safe-directory/ca.key
  with_items: "{{ play_hosts }}"
  when: inventory_hostname == play_hosts[0]

- name: synchronization of src on the inventory host to the dest on the localhost in pull mode
  ansible.posix.synchronize:
    mode: pull
    dirs: yes
    src: "{{ item }}"
    dest: "certificates"
  with_items: "{{ cert_folders }}"
  when: inventory_hostname == play_hosts[0]

- name: delete remote certificates folders
  ansible.builtin.file:
    state: absent
    path: "{{ item }}/"
  with_items: "{{ cert_folders }}"
  when: inventory_hostname == play_hosts[0]

- name: Copy file with owner and permissions
  ansible.builtin.copy:
    src:  "certificates/certs/{{ inventory_hostname }}/{{ item }}/"
    dest: "{{ crdb_cert_folder }}"
    owner: "{{ crdb_service_user }}"
    mode: '0600'
