- name: configure firewall (ufw)
  community.general.ufw:
    rule: allow
    proto: tcp
    port: '{{ item }}'
  loop:
    - "{{ ssh_port }}"
    - "{{ crdb_management_port }}"
    - "{{ crdb_sql_port }}"
    - "{{ crdb_rpc_port }}"
  when: ansible_os_family == 'Debian'

- name: configure firewall (firewalld)
  ansible.posix.firewalld:
    port: "{{ item ~ '/tcp' }}"
    permanent: yes
    immediate: yes
    state: enabled
  loop:
    - "{{ ssh_port }}"
    - "{ crdb_management_port }"
    - "{{ crdb_sql_port }}"
    - "{{ crdb_rpc_port }}"
  when: ansible_os_family == 'RedHat'