#
# Ref. https://www.cockroachlabs.com/docs/stable/deploy-cockroachdb-on-premises
#
- name: print inventory name
  ansible.builtin.debug:
    var: inventory_hostname

- name: print play host 0
  ansible.builtin.debug:
    var: play_hosts[0]

- name: set variables
  ansible.builtin.set_fact:
    certs_folder: certs
    safe_folder: my-safe-directory
    ca_crt: ca.crt
    ca_key: ca.key
    crdb_lb_items: "{{ ( crdb_lb_ip | default([]) ) + ( crdb_lb_hostnames | default([]) ) }}"

- name: "create base directory '{{ crdb_folder }}' if it does not exist"
  ansible.builtin.file:
    path: "{{ crdb_folder }}"
    state: directory
    mode: "0755"

- name: create certificate directories if they do not exist
  ansible.builtin.file:
    path: "{{ crdb_folder }}/{{ item }}"
    state: directory
    mode: "0755"
  loop:
    - "{{ certs_folder }}"
    - "{{ safe_folder }}"

- name: check if ca.crt exists
  ansible.builtin.stat:
    path: "{{ crdb_folder }}/{{ certs_folder }}/{{ ca_crt }}"
  register: ca_crt_stat

- name: check if ca.key exists
  ansible.builtin.stat:
    path: "{{ crdb_folder }}/{{ safe_folder }}/{{ ca_key }}"
  register: ca_key_stat

- name: check if root certificate needs to be generated
  ansible.builtin.set_fact:
    generate_ca_certs: "{{ (not (ca_crt_stat.stat.exists and ca_key_stat.stat.exists)) | bool }}"

- set_fact:
    generate_ca_certs: true

- name: debug
  ansible.builtin.debug:
    var: generate_ca_certs

- name: generate CA certificate and key on first node
  ansible.builtin.shell:
    cmd: >
      cockroach cert create-ca 
      --certs-dir={{ crdb_folder }}/{{ certs_folder }}/ 
      --ca-key={{ crdb_folder }}/{{ safe_folder }}/{{ ca_key }}
      --overwrite
      --allow-ca-key-reuse
  when:
    - generate_ca_certs
    - inventory_hostname == play_hosts[0]

- name: synchronize ca certs on first node to localhost
  ansible.posix.synchronize:
    mode: pull
    dirs: yes
    src: "{{ item }}"
    dest: "certificates"
  with_items:
    - "{{ crdb_folder }}/{{ certs_folder }}/{{ ca_crt }}"
    - "{{ crdb_folder }}/{{ safe_folder }}/{{ ca_key }}"
  when:
    - generate_ca_certs
    - inventory_hostname == play_hosts[0]

- name: "copy {{ ca_crt }} to other nodes"
  ansible.builtin.copy:
    src: "certificates/{{ certs_folder }}/{{ ca_crt }}"
    dest: "{{ crdb_folder }}/{{ certs_folder }}/"
    force: true
  when:
    - generate_ca_certs
    - inventory_hostname != play_hosts[0]

- name: "copy {{ ca_key }} to other nodes"
  ansible.builtin.copy:
    src: "certificates/{{ safe_folder }}/{{ ca_key }}"
    dest: "{{ crdb_folder }}/{{ safe_folder }}/"
    force: true
  when:
    - generate_ca_certs
    - inventory_hostname != play_hosts[0]

