#
# Ref. https://www.cockroachlabs.com/docs/stable/deploy-cockroachdb-on-premises
#
- name: print inventory name
  ansible.builtin.debug:
    var: inventory_hostname

- name: print play host 0
  ansible.builtin.debug:
    var: play_hosts[0]

- name: set variables
  ansible.builtin.set_fact:
    certs_folder: certs
    safe_folder: my-safe-directory
    ca_crt: ca.crt
    ca_key: ca.key
    node_crt: node.crt
    node_key: node.key
    client_root_crt: client.root.crt
    client_root_key: client.root.key
    crdb_lb_items: "{{ ( crdb_lb_ips | default([]) ) + ( crdb_lb_hostnames | default([]) ) }}"

- name: "create base directory '{{ crdb_folder }}' if it does not exist"
  ansible.builtin.file:
    path: "{{ crdb_folder }}"
    state: directory
    mode: "0755"

- name: create certificate directories if they do not exist
  ansible.builtin.file:
    path: "{{ crdb_folder }}/{{ item }}"
    state: directory
    mode: "0755"
  loop:
    - "{{ certs_folder }}"
    - "{{ safe_folder }}"

- name: check if ca.crt exists
  ansible.builtin.stat:
    path: "{{ crdb_folder }}/{{ certs_folder }}/{{ ca_crt }}"
  register: ca_crt_stat

- name: check if ca.key exists
  ansible.builtin.stat:
    path: "{{ crdb_folder }}/{{ safe_folder }}/{{ ca_key }}"
  register: ca_key_stat

- name: check if root certificate needs to be generated
  ansible.builtin.set_fact:
    generate_ca_certs: "{{ (not (ca_crt_stat.stat.exists and ca_key_stat.stat.exists)) | bool }}"

- set_fact:
    generate_ca_certs: true

- name: debug
  ansible.builtin.debug:
    var: generate_ca_certs

- name: generate CA certificate and key on first node
  ansible.builtin.shell:
    cmd: >
      cockroach cert create-ca 
      --certs-dir={{ crdb_folder }}/{{ certs_folder }}/ 
      --ca-key={{ crdb_folder }}/{{ safe_folder }}/{{ ca_key }}
      --overwrite
      --allow-ca-key-reuse
  when:
    - generate_ca_certs
    - inventory_hostname == play_hosts[0]

- name: synchronization of src on the inventory host to the dest on the localhost in pull mode
  ansible.posix.synchronize:
    mode: pull
    dirs: yes
    src: "{{ item }}"
    dest: "certificates"
  with_items:
    - "{{ crdb_folder }}/{{ certs_folder }}/"
    - "{{ crdb_folder }}/{{ safe_folder }}/"
  when:
    - generate_ca_certs
    - inventory_hostname == play_hosts[0]

- name: Copy CA cert and key with owner and permissions
  ansible.builtin.copy:
    src:  "certificates/"
    dest: "{{ crdb_folder }}"
    owner: "{{ crdb_service_user }}"
    group: "{{ crdb_service_group }}"
    mode: '0664'
    force: true
  when:
    - generate_ca_certs
    - inventory_hostname != play_hosts[0]

- name: "check if {{ node_crt }} exists"
  ansible.builtin.stat:
    path: "{{ crdb_folder }}/{{ certs_folder }}/{{ node_crt }}"
  register: node_crt_stat

- name: "check if {{ node_key }} exists"
  ansible.builtin.stat:
    path: "{{ crdb_folder }}/{{ safe_folder }}/{{ node_key }}"
  register: node_key_stat

- name: check if node certificate needs to be generated
  ansible.builtin.set_fact:
    generate_node_certs: "{{ (not (node_crt_stat.stat.exists and node_key_stat.stat.exists)) | bool }}"

- name: generate crdb node certificates
  ansible.builtin.shell:
    cmd: >
      cockroach cert create-node 
      {{ ansible_fqdn }}
      {{ ansible_hostname }}
      {{ ansible_host }}
      localhost
      127.0.0.1
      {{ crdb_lb_items | join(' ') }}
      --certs-dir={{ crdb_folder }}/{{ certs_folder }}
      --ca-key={{ crdb_folder }}/{{ safe_folder }}/{{ ca_key }}
      --overwrite
  when:
    - generate_node_certs

- name: "check if {{ client_root_crt }} exists"
  ansible.builtin.stat:
    path: "{{ crdb_folder }}/{{ certs_folder }}/{{ client_root_crt }}"
  register: client_crt_stat
  when:
    - inventory_hostname == play_hosts[0]

- name: "check if {{ client_root_key }} exists"
  ansible.builtin.stat:
    path: "{{ crdb_folder }}/{{ safe_folder }}/{{ client_root_key }}"
  register: client_key_stat
  when:
    - inventory_hostname == play_hosts[0]

- name: check if client certificate needs to be generated
  ansible.builtin.set_fact:
    generate_client_certs: "{{ (not (client_crt_stat.stat.exists and client_key_stat.stat.exists)) | bool }}"
  when:
    - inventory_hostname == play_hosts[0]

- name: generate cockroach client root user certificate
  ansible.builtin.shell:
    cmd: >
      cockroach cert create-client 
      root
      --certs-dir={{ crdb_folder }}/{{ certs_folder }}
      --ca-key={{ crdb_folder }}/{{ safe_folder }}/{{ ca_key }}
      --overwrite
  when:
    - inventory_hostname == play_hosts[0]
    - generate_client_certs
