- name: include OS specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: configure limits.conf
  ansible.builtin.blockinfile:
    path: /etc/security/limits.conf
    insertafter: EOF
    block: |
      *              soft     nofile          65536
      *              hard     nofile          65536
  register: limits_conf_st

- name: rebooting machine
  ansible.builtin.reboot:
    reboot_timeout: 300
  when: limits_conf_st.changed

- name: download and extract Cockroach DB executable
  ansible.builtin.unarchive:
    src: "{{ crdb_url }}"
    dest: /opt/
    remote_src: yes

- name: extract cockroach version
  ansible.builtin.set_fact:
    crdb_version: "{{ ((crdb_url | basename) | splitext)[0] }}"

- name: print cockroach version
  ansible.builtin.debug:
    var: crdb_version

- name: create cockroach folder symlink
  ansible.builtin.file:
    src: "/opt/{{ crdb_version }}"
    dest: "{{ crdb_folder }}"
    state: link
  register: folder_symlink

- name: create cockroach binary symlink
  ansible.builtin.file:
    src: "{{ crdb_folder }}/cockroach"
    dest: "{{ crdb_executable }}"
    state: link

- ansible.builtin.debug:
    var: hostvars

- name: generate hosts file
  ansible.builtin.include_tasks: hosts_file.yml
  when: (use_hosts_file | default(os_create_hosts_file) | bool)


