- name: gather hardware facts
  ansible.builtin.setup:
    gather_subset:
      - hardware

- name: get disks (/dev/sd*) except sda (OS)
  set_fact:
    disks: "{{ disks|default([]) + [ '/dev/' ~ item ] }}"
  loop: "{{ hostvars[inventory_hostname].ansible_devices.keys() | map('regex_search', 'sd([b-z]+|[a-z]{2})') | select('string') | list | sort }}"

- name: list disks
  ansible.builtin.debug:
    var: disks
    verbosity: 2

- name: get mounted devices
  set_fact:
    mounted_disks: "{{ ansible_mounts|json_query('[].device') }}"

- name: list mounted disks
  ansible.builtin.debug:
    var: mounted_disks
    verbosity: 2

- name: partition disks
  community.general.parted:
    device: "{{ item }}"
    number: 1
    state: present
  when: item not in mounted_devices
  loop: "{{ disks }}"

- name: create filesystem
  filesystem:
    fstype: "{{ filesystem | default(default_filesystem) }}"
    dev: "{{ item }}1"
  when: item not in mounted_devices
  loop: "{{ disks }}"

- name: mount data volumes
  mount:
    src: "{{ item }}1"
    path: "/data{{ my_index }}"
    opts: defaults
    state: mounted
    fstype: "{{ filesystem | default(default_filesystem) }}"
  when: item not in mounted_devices
  loop: "{{ vars.disks }}"
  loop_control:
    index_var: my_index