---
# Update hosts file CRDB node hostnames/IP
os_create_hosts_file: true

# URL for downloading the cockroach binary
# ref. https://www.cockroachlabs.com/docs/releases/
crdb_url: https://binaries.cockroachdb.com/cockroach-v23.2.2.linux-amd64.tgz


crdb_service_user: cockroach
crdb_service_group: cockroach

# Servers should advertise IP rather than hostname
advertise_ip: True

# SSH Port
ssh_port: 22

# Cockroach DB PSQL port
crdb_sql_port: 26257
crdb_rpc_port: 26357

# Cockroach DB management port
crdb_management_port: 8080

# CRDB parameters
crdb_rack_count: 1

# https://www.cockroachlabs.com/docs/stable/cluster-settings.html
# value: 'any', 'local', 'off'
crdb_remote_debugging_mode: 'off'

# List of data disks (e.g. ['/data0', '/data1']
crdb_data_disks: []

# CRDB executable installation path
crdb_folder: /opt/cockroach
crdb_executable: /usr/local/bin/cockroach

# Use PTP
crdb_ptp: True
crdb_ptp_dev: /dev/ptp0

# Use SSL
crdb_ssl: False
crdb_ssl_mode_disable: disable
crdb_ssl_mode_secure: verify-full&sslrootcert=/root/certs/ca.crt&sslcert=/root/certs/client.root.crt&sslkey=/root/certs/client.root.key

# CRDB systemd service name
crdb_service: cockroachdb

# Template for systemd service
crdb_service_template: cockroachdb.service.j2

# URL for downloading the workload binary
workload_url: https://edge-binaries.cockroachdb.com/cockroach/workload.LATEST

# workload executable
workload_executable: /usr/local/bin/workload