---
# Update hosts file CRDB node hostnames/IP
crdb_default_use_hosts_file: true

# Data disk properties
crdb_default_data_filesystem: xfs

# SSL
crdb_default_use_ssl: true
crdb_secure_flag: --certs-dir=/var/lib/cockroach/certs
crdb_insecure_flag: --insecure

# Load Balancer
crdb_default_lb_ips: []
crdb_default_lb_hostnames: []

# URL for downloading the cockroach binary
# ref. https://www.cockroachlabs.com/docs/releases/
crdb_url: https://binaries.cockroachdb.com/cockroach-v23.2.2.linux-amd64.tgz

# Service User and Group
crdb_service_user: cockroach
crdb_service_group: cockroach

# Default database account
crdb_default_db_user: cockroach
crdb_default_db_password: cockroach

# Cockroach DB management port
crdb_management_port: 8080

# Cockroach DB PSQL port
crdb_sql_port: 26257
crdb_rpc_port: 26357

# https://www.cockroachlabs.com/docs/stable/cluster-settings.html
# value: 'any', 'local', 'off'
crdb_remote_debugging_mode: 'off'

# List of data disks (e.g. ['/data0', '/data1']
crdb_data_disks: []

# CRDB executable installation path
crdb_folder: /var/lib/cockroach
crdb_cert_folder: /var/lib/cockroach/certs
crdb_executable: /usr/local/bin/cockroach

# Use PTP
crdb_ptp: True
crdb_ptp_dev: /dev/ptp0

# CRDB systemd service name
crdb_service: cockroachdb

# Template for systemd service
crdb_service_template: cockroachdb.service.j2

# URL for downloading the workload binary
workload_url: https://edge-binaries.cockroachdb.com/cockroach/workload.LATEST

# workload executable
workload_executable: /usr/local/bin/workload

# SSH Port
ssh_port: 22
