---
# Update hosts file CRDB node hostnames/IP
os_create_hosts_file: True

# URL for downloading the cockroach binary
# ref. https://www.cockroachlabs.com/docs/releases/
crdb_url: https://binaries.cockroachdb.com/cockroach-v23.2.2.linux-amd64.tgz

# Servers should advertise IP rather than hostname
advertise_ip: True

# Cockroach DB PSQL port
crdb_db_port: 26257

# Cockroach DB management port
crdb_management_port: 8080

# CRDB parameters
crdb_rack_count: 1

# https://www.cockroachlabs.com/docs/stable/cluster-settings.html
# value: 'any', 'local', 'off'
crdb_remote_debugging_mode: 'off'

# CRDB executable installation path
crdb_folder: /opt/cockroach
crdb_executable: /usr/local/bin/cockroach

# Use PTP
crdb_ptp: True
crdb_ptp_dev: /dev/ptp0

# Use SSL
crdb_ssl: False
crdb_ssl_mode_disable: disable
crdb_ssl_mode_secure: verify-full&sslrootcert=/root/certs/ca.crt&sslcert=/root/certs/client.root.crt&sslkey=/root/certs/client.root.key

# URL for downloading the workload binary
workload_url: https://edge-binaries.cockroachdb.com/cockroach/workload.LATEST

# workload executable
workload_executable: /usr/local/bin/workload